# Generated by Django 6.0.1 on 2026-01-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('language', models.CharField(default='auto', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('clipping', 'Clipping'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('original_path', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('score', models.FloatField(default=0)),
                ('caption', models.TextField(blank=True)),
                ('output_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='clips.videojob')),
            ],
        ),
    ]
