# Generated by Django 5.2.10 on 2026-01-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_videoclip_transcript_data_alter_videoclip_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoclip',
            name='transcript_data',
        ),
        migrations.AddField(
            model_name='videojob',
            name='transcript_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
