# Generated by Django 5.2.10 on 2026-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_remove_videoclip_transcript_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='transcript_path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
