# Generated by Django 5.2.10 on 2026-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_videojob_transcript_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.CharField(max_length=64)),
                ('creator_id', models.IntegerField()),
                ('channel', models.CharField(max_length=32)),
                ('retention_3s', models.FloatField()),
                ('retention_50p', models.FloatField()),
                ('retention_100p', models.FloatField()),
                ('hooks', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
