# Generated by Django 5.2.10 on 2026-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_clipfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('clipping', 'Clipping'), ('done', 'Done'), ('error', 'Error'), ('tracking_faces', 'Tracking_Faces')], default='pending', max_length=20),
        ),
    ]
