# Generated by Django 5.2.10 on 2026-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_videojobstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojobstep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
