# Generated by Django 5.2.10 on 2026-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_alter_videojobstep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='video_profile',
            field=models.CharField(default='podcast', max_length=50),
        ),
    ]
