# Generated by Django 5.2.10 on 2026-01-19 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0009_videojob_video_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_api_key', models.CharField(blank=True, max_length=255)),
                ('tiktok_api_secret', models.CharField(blank=True, max_length=255)),
                ('tiktok_access_token', models.TextField(blank=True)),
                ('instagram_access_token', models.TextField(blank=True)),
                ('instagram_account_id', models.CharField(blank=True, max_length=100)),
                ('youtube_client_id', models.CharField(blank=True, max_length=255)),
                ('youtube_client_secret', models.CharField(blank=True, max_length=255)),
                ('youtube_refresh_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20)),
                ('platform_video_id', models.CharField(max_length=255)),
                ('share_url', models.URLField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='published', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='clips.videoclip')),
            ],
            options={
                'unique_together': {('clip', 'platform')},
            },
        ),
    ]
