# Generated by Django 5.2.10 on 2026-01-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_socialmediacredentials_publishedclip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediacredentials',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublishedClip',
        ),
        migrations.DeleteModel(
            name='SocialMediaCredentials',
        ),
    ]
