# Generated by Django 5.2.10 on 2026-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_clippublication'),
        ('clips', '0011_remove_socialmediacredentials_user_and_more'),
    ]

    operations = [
    ]
