# Generated by Django 5.2.10 on 2026-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_merge_20260119_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippublication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
