# Generated by Django 5.2.10 on 2026-01-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0017_storyclippublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyclip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storyclippublication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
