# Generated by Django 5.2.10 on 2026-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('views', models.BigIntegerField()),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('engagement_rate', models.FloatField()),
                ('viral_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
